name: "Random Fun Fact in README"

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-fun-fact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Pull latest changes
        run: git pull origin main

      - name: Fetch random fun fact
        id: get_fact
        run: |
          echo "Fetching fun fact..."
          response=$(curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en")
          echo "Response: $response"
          fact=$(echo "$response" | jq -r .text)
          echo "FACT=$fact" >> $GITHUB_ENV

      - name: Update README.md
  run: |
    start="<!-- FUN_FACT_START -->"
    end="<!-- FUN_FACT_END -->"
    fact="${{ env.FACT }}"
    awk -v s="$start" -v e="$end" -v f="$fact" '
      BEGIN {p=1}
      $0~s {print; print "**Fun Fact of the Day:** " f; p=0; next}
      $0~e {p=1}
      p
    ' README.md > README.tmp && mv README.tmp README.md


      - name: Commit changes
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m 'chore: update fun fact in README [auto]'
        continue-on-error: true

      - name: Push changes
        run: |
          git push origin main
